Added expiration time to jobs
Wolox/async-requests pull request #20
Opened 2019-08-27 15:26 UTC by petaalcala

# Summary

- Added a new feature to prevent saving forever the request's responses done with the gem.

2019-08-27 15:41 UTC, holywyvern requested changes

2019-09-02 05:04 UTC, holywyvern approved these changes

2019-11-07 14:12 UTC, santyalcala commented on spec/factories/async_request_job.rb
> +FactoryGirl.define do
I tried but I couldn't 🤷‍♂

2021-03-19 17:13 UTC, petaalcala commented
@icoluccio

2022-04-07 20:06 UTC, closed without merging

2022-04-07 21:01 UTC, aleochoam commented
F